db:
  build: Dockers/db
  ports:
    - 5433:5432
es:
  build: Dockers/es
  ports:
    - 9203:9200
redis:
  image: redis:2.8
  ports:
    - 6373:6379
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/home/docker/hellolily
  ports:
    - 8003:8000
  links:
    - db
    - es
    - rabbit
    - redis
    - beat
    - worker
rabbit:
  build: Dockers/rabbit
beat:
  build: .
  command: celery worker -B --app=lily.celery --loglevel=info -Q celery -n beat.%h -c 1
  volumes: [".:/home/docker/hellolily"]
  links: [rabbit, db, redis, es]
worker:
  build: .
  command: celery worker --loglevel=debug --app=lily.celery -Q queue1 -n worker.%h -c 10 -P eventlet
  volumes: [".:/home/docker/hellolily"]
  links: [rabbit, db, redis, es]
