db:
  build: Dockers/db
  ports:
    - 5433:5432
es:
  build: Dockers/es
  ports:
    - 9203:9200
redis:
  image: redis:2.8
  ports:
    - 6373:6379
base:
  build: .
  volumes:
    - .:/home/docker/hellolily
bash:
  extends:
    file: docker-compose.yml
    service: base
  command: bash
  links: [rabbit, db, redis, es]
manage:
  extends:
    file: docker-compose.yml
    service: base
  entrypoint: ['python', 'manage.py']
  command: []
  links: [rabbit, db, redis, es]
web:
  extends:
    file: docker-compose.yml
    service: base
  command: runserver 0.0.0.0:8000
  ports:
    - 8003:8000
  links:
    # Define all containers for easy running of development setup.
    - db
    - es
    - rabbit
    - redis
    - beat
    - worker1
    - worker2
rabbit:
  build: Dockers/rabbit
beat:
  extends:
    file: docker-compose.yml
    service: base
  command: celery worker -B --app=lily.celery --loglevel=info -Q celery -n beat.%h -c 1
  links: [rabbit, db, redis, es]
worker1:
  extends:
    file: docker-compose.yml
    service: base
  command: celery worker --loglevel=info --app=lily.celery -Q queue1 -n worker1.%h -c 12 -P eventlet
  links: [rabbit, db, redis, es]
worker2:
  extends:
    file: docker-compose.yml
    service: base
  command: celery worker --loglevel=info --app=lily.celery -Q queue2 -n worker2.%h -c 12 -P eventlet
  links: [rabbit, db, redis, es]
